package com.ust.testutils;

/**
 * This throws when testing auto generated class.
 */
public class AutoGeneratedClassTestingException extends RuntimeException {

    public AutoGeneratedClassTestingException(Throwable cause) {
        super(cause);
    }
}
